=== Iraitz-Elorrieta/markak3ebal/azterketaebal3+repaso/AzterketaIraitz3ebal/irakasleak.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="irakasleak">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="irakaslea" minOccurs="1" maxOccurs="unbounded">
					
					<xs:complexType>
						<xs:sequence>
							<xs:element name="izena" type="xs:string"></xs:element>
							<xs:element name="modulua" type="xs:string" minOccurs="1" maxOccurs="5">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="antzinetasuna" type="xs:date"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

<!-- <xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{8}[a-zA-Z]"/>
		</xs:restriction>
	</xs:simpleType>-->

=== Iraitz-Elorrieta/markak3ebal/azterketaebal3+repaso/AzterketaIraitz3ebal/irakasleak.xml
<?xml version="1.0" encoding="UTF-8"?>
<irakasleak
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="irakasleak.xsd">

	<irakaslea nan="12345678-X">
		<izena>Bego√±a Zurimendi</izena>
		<modulua>PGR</modulua>
		<modulua>PSP</modulua>
		<antzinetasuna
			lehenIkastetxea="Elorrieta-Errekamari LHII">2005-09-01</antzinetasuna>
		<tutorea kurtsoa="1" />
	</irakaslea>
	<irakaslea nan="23456789-A">
		<izena>Jone Garatea</izena>
		<modulua>GBD</modulua>
		<modulua>ABD</modulua>
		<antzinetasuna>2010-09-01</antzinetasuna>
		<mintegiBurua />
	</irakaslea>
	<irakaslea nan="77788899-Z">
		<izena>Isabel Azkunaga</izena>
		<modulua>EDE</modulua>
		<modulua>PSP</modulua>
	</irakaslea>
	<irakaslea nan="22255512-T">
		<izena>Luke Gainza</izena>
		<modulua>LMS</modulua>
		<modulua>GBD</modulua>
		<tutorea kurtsoa="1" />
	</irakaslea>
	<irakaslea nan="45678912-P">
		<izena>Andoni Egileor</izena>
		<modulua>SIS</modulua>
		<modulua>SGE</modulua>
		<modulua>DIN</modulua>
		<tutorea kurtsoa="2" />
	</irakaslea>
	<irakaslea nan="44455555-N">
		<izena>Oier Aranguren</izena>
		<modulua>PRG</modulua>
		<modulua>FCT</modulua>
		<modulua>EDE</modulua>
	</irakaslea>
</irakasleak>
