=== Iraitz-Elorrieta/markak3ebal/markak3ebal/ikasleak.xml Ariketak III EBATZITA-20240520/ikasleak06.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--Datu moten definizioa-->
<xs:complexType name="helbideaDatua">
    <xs:sequence>
        <xs:element name="kalea" type="xs:string"></xs:element>
        <xs:element name="zbk">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"></xs:minInclusive>
                    <xs:maxInclusive value="1000"></xs:maxInclusive>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="herria" type="xs:string"></xs:element>
        <xs:element name="probintzia" type="xs:string"></xs:element>
    </xs:sequence>
</xs:complexType>



    <xs:element name="ikasleak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ikaslea" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        
                        <xs:element name="izena" type="xs:string"></xs:element>
                        <xs:element name="helbidea" type="helbideaDatua"></xs:element>
                        <xs:choice>
                            <xs:element name="telefonoa" type="xs:integer"></xs:element>
                            <xs:element name="mugikorra" type="xs:integer" maxOccurs="3"></xs:element>
                        </xs:choice>                            
                        <xs:element name="eposta" type="xs:string"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="nan" type="xs:integer" use="required"></xs:attribute>
                    <xs:attribute name="errepikatzailea" type="xs:boolean" default="false"></xs:attribute>
                    <xs:attribute name="jaiotzaData" type="xs:date" use="required"></xs:attribute>
                </xs:complexType>   
                </xs:element>
            </xs:sequence>
        </xs:complexType>   
    </xs:element>    
</xs:schema>

=== Iraitz-Elorrieta/markak3ebal/markak3ebal/ikasleak.xml Ariketak III EBATZITA-20240520/ikasleak06.xml
<?xml version="1.0" encoding="UTF-8"?>
<ikasleak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ikasleak06.xsd">
    <ikaslea nan="11111111" errepikatzailea="false" jaiotzaData="2000-01-12">        
        <izena>Iraide Etxeberria</izena>
        <helbidea>
            <kalea>Kale nagusia</kalea>
            <zbk>1000</zbk>
            <herria>Bilbao</herria>
            <probintzia>Bizkaia</probintzia>
        </helbidea>
        <telefonoa>944000000</telefonoa>
        <eposta>iraide@gmail.com</eposta>
    </ikaslea>
    <ikaslea nan="22222222" errepikatzailea="false" jaiotzaData="2000-05-01">
        <izena>Joseba Mikel Zarraga</izena>
        <helbidea>
            <kalea>Gorbeia</kalea>
            <zbk>75</zbk>
            <herria>Artea</herria>
            <probintzia>Bizkaia</probintzia>
        </helbidea>
        <mugikorra>644999999</mugikorra>
        <mugikorra>666777888</mugikorra>
        <eposta>joseba@gmail.com</eposta>
    </ikaslea>
</ikasleak>
