=== Iraitz-Elorrieta/markak3ebal/markak3ebal/fakturak/faktura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:simpleType name="Tid">
  <xs:restriction  base="xs:integer">
    <xs:minInclusive value="0"/>
    <xs:maxInclusive value="10000"/>
  </xs:restriction>
</xs:simpleType>



  <xs:element name="faktura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="f_data" type="xs:dateTime"/>
        <xs:element name=" saltzailea">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="izena" type="xs:string"/>
              <xs:element name="nan">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="\d{8}[a-zA-Z]"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="Tid" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="bezeroa">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="izena" type="xs:string"/>
            <xs:element name="helbidea">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="kalea" type="xs:string"/>
                  <xs:element name="kp" type="xs:integer"/>
                  <xs:element name="herria" type="xs:string"/>
                  <xs:element name="probintzia" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="telefonoa" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="num" type="xs:integer" use="required"/>
              </xs:complexType>
            </xs:element>            
          </xs:sequence>
          <xs:attribute name="id" type="Tid" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="artikulua" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="deskribapena" type="xs:string"/>
              <xs:element name="prezioa" type="xs:decimal"/>
              <xs:element name="kantitatea" type="xs:integer"/>
            </xs:sequence>
            <xs:attribute name="id" type="Tid" use="required"/>
            <xs:attribute name="bez" type="xs:integer" use="required"/>
          </xs:complexType>
          </xs:element>
          <xs:element name="deskontua" minOccurs="0">
            <xs:simpleType>
              <xs:restriction  base="xs:integer">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="100"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="Tid"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Iraitz-Elorrieta/markak3ebal/azterketaebal3+repaso/markak3ebal/fakturak/fakturak.xml
<?xml version="1.0" encoding="utf-8"?>
<faktura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="876" xsi:noNamespaceSchemaLocation="faktura.xsd">
  <f_data>2022-02-28T08:25:02</f_data>
  <saltzailea id="12">
    <izena>June Arriaga Zarate</izena>    
    <nan>12345678A</nan>
  </saltzailea>
  <bezeroa id="9878">
    <izena>Leire Bengoetxea Zallo</izena>
    <helbidea>
      <kalea>Kale Nagusia, 8, 2 - A</kalea>
      <kp>48300</kp>
      <herria>Gernika</herria>
      <probintzia>Bizkaia</probintzia>
    </helbidea>
    <telefonoa num="666111666"/>
    <telefonoa num="954666111"/>
  </bezeroa>
  <artikulua id="121" bez="21">
    <deskribapena>Aulki birakaria, C-121 modeloa</deskribapena>
    <prezioa>98.23</prezioa>
    <kantitatea>1</kantitatea>
  </artikulua>
  <artikulua id="9341" bez="21">
    <deskribapena>120x80 estudioko pago mahaia, A2-456-X modeloa</deskribapena>
    <prezioa>193.23</prezioa>
    <kantitatea>1</kantitatea>
  </artikulua>
  <artikulua id="1124" bez="21">
    <deskribapena>Pantaila laranjako mahaiko lanpara, AK-987 modeloa</deskribapena>
    <prezioa>23.12</prezioa>
    <kantitatea>2</kantitatea>    
  </artikulua>
  <deskontua>20</deskontua>
</faktura>
