=== Iraitz-Elorrieta/markak3ebal/markak3ebal/XML Schema. Ariketak Errepasoa-20240520/cancion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


	<xs:element name="canciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cancion" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titulo" type="xs:string" maxOccurs="1" />
							<xs:element name="compositores" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="compositor" maxOccurs="2">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="nombre" type="xs:string" />
													<xs:element name="apellido" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="productores" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="productor" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="nombre" type="xs:string" />
													<xs:element name="apellido" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="sello" type="xs:string"/>
							<xs:element name="artista" type="xs:string"/>						
						</xs:sequence>
						<xs:attribute name="duracion" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[0-9]-[0-9][0-9]"/>
									</xs:restriction>
								</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="anio" type="xs:integer"
							use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Iraitz-Elorrieta/markak3ebal/azterketaebal3+repaso/markak3ebal/XML Schema. Ariketak Errepasoa-20240520/cancion.xml
<?xml version="1.0" encoding="UTF-8"?>

<canciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="cancion.xsd">
<cancion duracion="4:47" anio="2008">

	<titulo>Give it 2 me</titulo>
	<compositores>
		<compositor>
			<nombre>Pharrell</nombre>
			<apellido>Williams</apellido>
		</compositor>
	</compositores>
	<productores>
		<productor>
			<nombre>Pharrell</nombre>
			<apellido>Pharrell</apellido>			
		</productor>
	</productores>
	<sello>Warner Bros Records</sello>
	<artista>Madonna</artista>

</cancion>
</canciones>
